[package]
name = "dither"
version = "1.0.0"
authors = ["Efron Licht <efron.python@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A ditherer for PNG images"
repository= "https://gitlab.com/efronlicht/dither"

[dependencies]
structopt = "0.2"
image = "0.21.0"
lazy_static = "1.2.0"
regex="1.1.0"
[dev-dependencies]
rand = "0.6.5"
